//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusServiceEproject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

     
    public partial class tbl_usersignup
    {
        public int u_id { get; set; }
        [Required(ErrorMessage="*")]
        public string u_name { get; set; }
        [Required(ErrorMessage = "*")]
        public string u_Eamil { get; set; }
        [Required(ErrorMessage = "*")]
        public string u_Password { get; set; }
        [Required(ErrorMessage = "*")]
        public string Conform_Password { get; set; }
        [Required(ErrorMessage = "*")]
        public string u_Contact { get; set; }
        [Required(ErrorMessage = "*")]
        public string Image { get; set; }
    }
}
